version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-12345}
      MYSQL_DATABASE: ${DB_NAME:-driver_app}
    ports:
      - "33068:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    environment:
      NODE_ENV: development
      PORT: 3007
      JWT_SECRET: ${JWT_SECRET:-change_me_secret}
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: ${DB_PASS:-12345}
      DB_NAME: ${DB_NAME:-driver_app}
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3007:3007"

volumes:
  db_data:
